# redis.conf (local-only)

port 6379
bind 127.0.0.1 ::1
protected-mode yes

# 인증
requirepass farmonRedis1234

# 영속화(선택)
appendonly yes
appendfsync everysec

# 스냅샷(선택)
save 900 1
save 300 10
save 60 10000

# 로그(선택)
loglevel notice
databases 16

